
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2
      - name: Configuração do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Instalar dependências
        run: npm install
      - name: Build da aplicação
        run: npm run build
      - name: Deploy para produção
        run: |
          npm run deploy-production
