
name: CI - Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2
      - name: Configuração do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Instalar dependências
        run: npm install
        run: npm install --save-dev live-server
      - name: Rodar testes Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:3000/'
          wait-on-timeout: 60
